[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "1695e6140b676f2be356907b7044fa762157f5c1"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "8617f6f37dea8544883efedadc291858427cf79b16370769b844063a9ed32291"
    url = "https://github.com/ralna/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.0+0/GALAHAD.v5.2.0.aarch64-apple-darwin-libgfortran5.tar.gz"
