[[GALAHAD]]
arch = "aarch64"
git-tree-sha1 = "81a75309a7420810b84363d3fbc86f63772cadd3"
libgfortran_version = "5.0.0"
os = "macos"

    [[GALAHAD.download]]
    sha256 = "e2b91b88734b59bc0d5447fa9cb168bc0ac29d795cf02da7893781145bde01ce"
    url = "https://github.com/ralna/GALAHAD_jll.jl/releases/download/GALAHAD-v5.2.0+0/GALAHAD.v5.2.0.aarch64-apple-darwin-libgfortran5.tar.gz"
